### ISSUE TITLE
Add support for http://paste.scsys.co.uk/perl

### ISSUE THREAD

**Issue by sshiraga** [jhthorsen/mojolicious-plugin-linkembedder#11]
Much like pastes from Gist, it would be nice if pastes from paste.scsys.co.uk were supported as well.

**Comment by jhthorsen** [comment]
I believe this should be implemented with a shared code base so it can also support http://ssl.thorsen.pm/paste (mojopaste).

The idea is to be able to embed plain text.

Example:
http://paste.scsys.co.uk/453329?tx=on
https://ssl.thorsen.pm/paste/d1dd4f13264c.txt

Unfortunately this is not on my current TODO list and I'm not sure when I get time to do it.

**Comment by jhthorsen** [comment]
Same here: http://pastebin.com/JgcQLXyh vs http://pastebin.com/raw.php?i=JgcQLXyh

**Comment by jhthorsen** [comment]
And http://ix.io/hff

**Comment by jhthorsen** [comment]
I've add support for all of the above in release 0.21, except mojopaste.
