### ISSUE TITLE
MetaCPAN links embed as 404

### ISSUE THREAD

**Issue by jberger** [jhthorsen/mojolicious-plugin-linkembedder#14]
Admittedly I'm filing the bug against version 0.14 so perhaps this is fixed, but when cpan_mojo posts a link I see this:

http://imgur.com/YBXaPjE

**Comment by jhthorsen** [comment]
It doesn't show anything in 0.13. Probably because Mojolicious::Plugin::LinkEmbedder::Link::Text::Metacpan was added in 0.14.

**Comment by jberger** [comment]
Interestingly, after upgrading to 0.17 the embedding seems better. I can't close it yet though because I'm not sure if the problem is fixed or if cpan_mojo is simply posting the link before metacpan is ready (and then caching keeps it broken)

**Comment by jhthorsen** [comment]
It's because metacpan is not updated when we try to render the link... A bit weird, but I'm pretty sure that it's correct, since it's not rendered as 404 after a refresh.

Anyway, I'm now checking ```$tx->success``` before trying to fetch meta information.
