### ISSUE TITLE
Text paste inclusions can be too long

### ISSUE THREAD

**Issue by jberger** [jhthorsen/mojolicious-plugin-linkembedder#21]
Most of the time inlining an entire paste is ok, but sometimes it can be way too long, like the entire build log for a failed build of the perl interpreter :cry:. Can we either limit the paste lines to like <100 lines or else scope it to some kind of scroller?

Refs: https://github.com/jhthorsen/mojolicious-plugin-linkembedder/commit/f6fac12772798cb6bc463d2b4ca7d10f8f54e1c5 and #11

**Comment by jhthorsen** [comment]
I think this is a convos bug/enhancement request, but I will see if I can make this compatible with the gist styling. That way it will "just work"

**Comment by jhthorsen** [comment]
No longer maintained
