### ISSUE TITLE
Add support for fpaste.org

### ISSUE THREAD

**Issue by jberger** [jhthorsen/mojolicious-plugin-linkembedder#22]
Requested via IRC

**Comment by jhthorsen** [comment]
Thanks! Will try to do it next week.

**Comment by jhthorsen** [comment]
Want to also support:
* https://bitbucket.org/snippets/bpmedley/895ne
* mojopaste

**Comment by jhthorsen** [comment]
No longer maintained. Have a look at https://github.com/jhthorsen/linkembedder/issues instead.
